CREATE TABLE book (
  id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
  isbn VARCHAR(255) NOT NULL,
  name VARCHAR(255) NOT NULL,
  author VARCHAR(255) NOT NULL,
  summary VARCHAR(255) NOT NULL,
  publish_date DATE NOT NULL,
  available BIT
);

CREATE TABLE user (
  id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL,
  count_book INT DEFAULT 0
);

CREATE TABLE record (
  id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
  user_id INTEGER NOT NULL,
  book_id INTEGER NOT NULL,
  borrow_date DATE NOT NULL,
  expiry_date DATE NOT NULL,
  return_date DATE
);